name: Manter Sites Cejusc Acordados

on:
  schedule:
    # Roda a cada 12 minutos
    # Manhã: 12:00 às 14:00 UTC (09h às 11h Brasília)
    # Tarde: 16:00 às 19:00 UTC (13h às 16h Brasília)
    - cron: '*/12 12-14,16-19 * * 1-5'
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Acessando os sistemas do CEJUSC
        run: |
          curl -I https://fusor.onrender.com/
          curl -I https://extrator-pauta-cejusc.onrender.com/
          curl -I https://nomeacao-nova-web.onrender.com/
          curl -I https://dias-web-3.onrender.com/
          curl -I https://gerador-cejusc.onrender.com/
